name: 'Is this empty issue?'
description: This action checks if your GitHub Issue doesn't have any description after creation and editing. Desc < 125 characters
branding:
  icon: zap 
  color: purple
on: 
  workflow_call:
  inputs: 
    issue-number:
      required: true
jobs:
  check_empty_issue:
    if: github.event.issue.body == ''
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ inputs.issue-number }}
          body: |
            Forgetting something? This issue should have some sort of description 😉 (this is from main)
