name: 'Is this empty issue?'
description: This action checks if your GitHub Issue doesn't have any description after creation and editing. Also this is another text to check how much characters can we fit in this description. I see no linter screaming at me if I'm doing something wrong. So this one still feels okay. What's the usual character count of descriptions? Average number of characters?
branding:
  icon: battery-charging 
  color: red
on: 
  workflow_call:
  issues:
    types: [opened, edited]
jobs:
  check_empty_issue:
    if: github.event.issue.body == ''
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Forgetting something? This issue should have some sort of description 😉
